# Generated by Django 5.2.5 on 2025-09-15 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('Act_id', models.AutoField(primary_key=True, serialize=False)),
                ('Act_nombre', models.CharField(max_length=30)),
                ('Act_descripcion', models.TextField()),
                ('Act_fechaLimite', models.DateField()),
                ('Act_Archivo_Profesor', models.FileField(blank=True, null=True, upload_to='archivos/profesores/')),
            ],
            options={
                'db_table': 'actividad',
            },
        ),
        migrations.CreateModel(
            name='Boletin',
            fields=[
                ('Bol_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'boletin',
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('Cur_id', models.AutoField(primary_key=True, serialize=False)),
                ('Cur_nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'curso',
            },
        ),
        migrations.CreateModel(
            name='Directivos',
            fields=[
                ('Dir_id', models.AutoField(primary_key=True, serialize=False)),
                ('Dir_cargo', models.CharField(max_length=50)),
                ('Dir_telefono', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'directivos',
            },
        ),
        migrations.CreateModel(
            name='Estado_Actividad',
            fields=[
                ('Esta_Actividad_id', models.AutoField(primary_key=True, serialize=False)),
                ('Esta_Actividad_Estado', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'estado_actividad',
            },
        ),
        migrations.CreateModel(
            name='Estado_Asistencia',
            fields=[
                ('Esta_Asistencia_id', models.AutoField(primary_key=True, serialize=False)),
                ('Esta_Asistencia_Estado', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'estado_asistencia',
            },
        ),
        migrations.CreateModel(
            name='Estudiantes',
            fields=[
                ('Est_id', models.AutoField(primary_key=True, serialize=False)),
                ('Est_direccion', models.CharField(max_length=100)),
                ('Est_añoAcademico', models.CharField(choices=[('transicion', 'Transición'), ('primero', 'Primero'), ('segundo', 'Segundo'), ('tercero', 'Tercero'), ('cuarto', 'Cuarto'), ('quinto', 'Quinto'), ('sexto', 'Sexto'), ('septimo', 'Séptimo'), ('octavo', 'Octavo'), ('noveno', 'Noveno'), ('decimo', 'Décimo'), ('once', 'Once')], max_length=30, verbose_name='Grado académico')),
                ('Est_tipoJornada', models.CharField(choices=[('mañana', 'Mañana'), ('tarde', 'Tarde'), ('noche', 'Noche'), ('completa', 'Jornada Completa'), ('sabatina', 'Sabatina'), ('dominical', 'Dominical')], max_length=30, verbose_name='Tipo de jornada')),
                ('Est_enfermedad', models.CharField(max_length=30)),
                ('Est_eps', models.CharField(choices=[('nueva_eps', 'Nueva EPS'), ('sanitas', 'Sanitas'), ('sura', 'Sura'), ('compensar', 'Compensar'), ('famisanar', 'Famisanar'), ('salud_total', 'Salud Total'), ('coomeva', 'Coomeva'), ('medimas', 'Medimás'), ('colsanitas', 'Colsanitas'), ('cafesalud', 'Cafesalud'), ('golden_group', 'Golden Group'), ('aliansalud', 'Aliansalud'), ('mutual_ser', 'Mutual Ser'), ('coosalud', 'Coosalud'), ('capresoca', 'Capresoca'), ('comfenalco', 'Comfenalco'), ('ecoopsos', 'Ecoopsos'), ('emssanar', 'Emssanar'), ('salud_vida', 'Salud Vida'), ('otra', 'Otra')], max_length=30, verbose_name='EPS')),
                ('Est_colegioAnterior', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'estudiantes',
            },
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('Mtr_id', models.AutoField(primary_key=True, serialize=False)),
                ('Mtr_nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'materia',
            },
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('Per_id', models.AutoField(primary_key=True, serialize=False)),
                ('Per_nombre', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'periodo',
            },
        ),
        migrations.CreateModel(
            name='Profesores',
            fields=[
                ('Pro_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'profesores',
            },
        ),
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('Tus_id', models.AutoField(primary_key=True, serialize=False)),
                ('TusTiposUsuario', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'TipoUsuario',
            },
        ),
        migrations.CreateModel(
            name='Actividad_Entrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Act_fecha_entrega', models.DateField(auto_now_add=True)),
                ('Act_calificacion', models.FloatField(blank=True, null=True)),
                ('Act_comentario', models.CharField(max_length=100)),
                ('Act', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='zainoAcademy_app.actividad')),
                ('Est', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zainoAcademy_app.estudiantes')),
            ],
            options={
                'db_table': 'actividad_entrega',
                'unique_together': {('Act', 'Est')},
            },
        ),
        migrations.CreateModel(
            name='Actividad_EntregaArchivo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('archivo', models.FileField(upload_to='archivos/estudiantes/')),
                ('entrega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='zainoAcademy_app.actividad_entrega')),
            ],
            options={
                'db_table': 'actividad_entrega_archivo',
            },
        ),
        migrations.AddField(
            model_name='actividad',
            name='Bol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zainoAcademy_app.boletin'),
        ),
        migrations.AddField(
            model_name='boletin',
            name='Cur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zainoAcademy_app.curso'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='Esta_Actividad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zainoAcademy_app.estado_actividad'),
        ),
        migrations.CreateModel(
            name='Estudiante_Curso',
            fields=[
                ('Est_Cur_id', models.AutoField(primary_key=True, serialize=False)),
                ('Cur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zainoAcademy_app.curso')),
                ('Est', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zainoAcademy_app.estudiantes')),
            ],
            options={
                'db_table': 'Estudiante_Curso',
            },
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('Ast_id', models.AutoField(primary_key=True, serialize=False)),
                ('Ast_fecha', models.DateField()),
                ('Esta_Asistencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zainoAcademy_app.estado_asistencia')),
                ('Est_Cur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zainoAcademy_app.estudiante_curso')),
            ],
            options={
                'db_table': 'asistencia',
            },
        ),
        migrations.AddField(
            model_name='boletin',
            name='Mtr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zainoAcademy_app.materia'),
        ),
        migrations.CreateModel(
            name='MaterialApoyo',
            fields=[
                ('Mate_id', models.AutoField(primary_key=True, serialize=False)),
                ('Mate_descripcion', models.CharField(max_length=100)),
                ('Mate_titulo', models.CharField(max_length=100)),
                ('Mate_archivo', models.FileField(blank=True, null=True, upload_to='materiales_apoyo/')),
                ('Bol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zainoAcademy_app.boletin')),
            ],
            options={
                'db_table': 'material_de_apoyo',
            },
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('Mat_id', models.AutoField(primary_key=True, serialize=False)),
                ('Mat_nivel', models.CharField(choices=[('transicion', 'Transición'), ('primaria', 'Primaria'), ('secundaria', 'Secundaria'), ('media', 'Media')], max_length=50, verbose_name='Nivel académico')),
                ('Mat_fecha', models.DateField()),
                ('Mat_estado', models.CharField(max_length=30)),
                ('Mat_metodo_pago', models.CharField(max_length=30)),
                ('Mat_comprobante', models.FileField(blank=True, null=True, upload_to='matricula/')),
                ('Mat_valor', models.CharField(max_length=30)),
                ('Mat_fecha_pago', models.DateField()),
                ('Directivos_Dir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zainoAcademy_app.directivos')),
                ('Estudiantes_Est', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zainoAcademy_app.estudiantes')),
            ],
            options={
                'db_table': 'matricula',
            },
        ),
        migrations.AddField(
            model_name='boletin',
            name='Per',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zainoAcademy_app.periodo'),
        ),
        migrations.AddField(
            model_name='boletin',
            name='Pro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zainoAcademy_app.profesores'),
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('Us_id', models.AutoField(primary_key=True, serialize=False)),
                ('Us_nombre', models.CharField(max_length=30)),
                ('Us_contraseña', models.CharField(max_length=30)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('documento', models.CharField(max_length=30)),
                ('genero', models.CharField(choices=[('masculino', 'Masculino'), ('femenino', 'Femenino'), ('otro', 'Otro'), ('prefiero_no_decir', 'Prefiero no decir')], max_length=30)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('foto_perfil_usuario', models.ImageField(blank=True, null=True, upload_to='fotos_perfil/')),
                ('TipoUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zainoAcademy_app.tipousuario')),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
        migrations.AddField(
            model_name='profesores',
            name='Us',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zainoAcademy_app.usuario'),
        ),
        migrations.AddField(
            model_name='estudiantes',
            name='Usuario_us',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zainoAcademy_app.usuario'),
        ),
        migrations.AddField(
            model_name='directivos',
            name='Us',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zainoAcademy_app.usuario'),
        ),
        migrations.CreateModel(
            name='Acudiente',
            fields=[
                ('Acu_id', models.AutoField(primary_key=True, serialize=False)),
                ('Estudiantes_Est', models.ManyToManyField(related_name='acudientes', to='zainoAcademy_app.estudiantes')),
                ('Usuario_Us', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zainoAcademy_app.usuario')),
            ],
        ),
    ]
