# Generated by Django 5.2.4 on 2025-09-16 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zainoAcademy_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matricula',
            name='Mat_tipo',
            field=models.CharField(choices=[('normal', 'Normal'), ('repitente', 'Repitente'), ('promovido', 'Promovido')], default='normal', max_length=20),
        ),
    ]
