# Generated by Django 5.2 on 2025-09-22 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zainoAcademy_app', '0002_matricula_mat_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad_entrega',
            name='Act_comentario',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
