# Generated by Django 5.2.3 on 2025-09-02 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zainoAcademy_app', '0002_alter_usuario_fecha_registro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiantes',
            name='Est_añoAcademico',
            field=models.CharField(choices=[('transicion', 'Transición'), ('primero', 'Primero'), ('segundo', 'Segundo'), ('tercero', 'Tercero'), ('cuarto', 'Cuarto'), ('quinto', 'Quinto'), ('sexto', 'Sexto'), ('septimo', 'Séptimo'), ('octavo', 'Octavo'), ('noveno', 'Noveno'), ('decimo', 'Décimo'), ('once', 'Once')], max_length=30, verbose_name='Grado académico'),
        ),
        migrations.AlterField(
            model_name='estudiantes',
            name='Est_eps',
            field=models.CharField(choices=[('nueva_eps', 'Nueva EPS'), ('sanitas', 'Sanitas'), ('sura', 'Sura'), ('compensar', 'Compensar'), ('famisanar', 'Famisanar'), ('salud_total', 'Salud Total'), ('coomeva', 'Coomeva'), ('medimas', 'Medimás'), ('colsanitas', 'Colsanitas'), ('cafesalud', 'Cafesalud'), ('golden_group', 'Golden Group'), ('aliansalud', 'Aliansalud'), ('mutual_ser', 'Mutual Ser'), ('coosalud', 'Coosalud'), ('capresoca', 'Capresoca'), ('comfenalco', 'Comfenalco'), ('ecoopsos', 'Ecoopsos'), ('emssanar', 'Emssanar'), ('salud_vida', 'Salud Vida'), ('otra', 'Otra')], max_length=30, verbose_name='EPS'),
        ),
        migrations.AlterField(
            model_name='estudiantes',
            name='Est_tipoJornada',
            field=models.CharField(choices=[('mañana', 'Mañana'), ('tarde', 'Tarde'), ('noche', 'Noche'), ('completa', 'Jornada Completa'), ('sabatina', 'Sabatina'), ('dominical', 'Dominical')], max_length=30, verbose_name='Tipo de jornada'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='genero',
            field=models.CharField(choices=[('masculino', 'Masculino'), ('femenino', 'Femenino'), ('otro', 'Otro'), ('prefiero_no_decir', 'Prefiero no decir')], max_length=30),
        ),
    ]
