# Generated by Django 5.2.5 on 2025-09-03 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zainoAcademy_app', '0003_alter_estudiantes_est_añoacademico_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acudiente',
            name='Estudiantes_Est',
        ),
        migrations.AlterField(
            model_name='matricula',
            name='Mat_nivel',
            field=models.CharField(choices=[('transicion', 'Transición'), ('primaria', 'Primaria'), ('secundaria', 'Secundaria'), ('media', 'Media')], max_length=50, verbose_name='Nivel académico'),
        ),
        migrations.AlterModelTable(
            name='acudiente',
            table=None,
        ),
        migrations.AddField(
            model_name='acudiente',
            name='Estudiantes_Est',
            field=models.ManyToManyField(related_name='acudientes', to='zainoAcademy_app.estudiantes'),
        ),
    ]
