# Generated by Django 5.2.3 on 2025-09-08 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zainoAcademy_app', '0004_remove_acudiente_estudiantes_est_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividad_entrega',
            name='Act_Archivo_Estudiante',
        ),
        migrations.CreateModel(
            name='Actividad_EntregaArchivo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('archivo', models.FileField(upload_to='archivos/estudiantes/')),
                ('entrega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='zainoAcademy_app.actividad_entrega')),
            ],
            options={
                'db_table': 'actividad_entrega_archivo',
            },
        ),
    ]
